version: '3.8'
services:
  mysql:
    container_name: mysql-book-network
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Raviteja@1968
      MYSQL_DATABASE: booknetwork
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql-data:
    driver: local
